chizography-preview:
    build: .
    expose:
      - 80
    environment:
      VIRTUAL_HOST: preview.chizography.net
      HTTPS_METHOD: noredirect
    volumes:
        - ./conf/.well-known:/var/www/.well-known
