<!-- footer.inc -->
    <div id="footer">
      <div class="container">
        <p class="text-muted credit">[%copyright%]</p>
      </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="/bootstrap/holder.min.js"></script>
    [% PROCESS googleanalytics.inc %]
  </body>
</html>
<!-- footer.inc -->
