<!-- Place this tag where you want the widget to render. -->
<div class="g-person" data-href="//plus.google.com/104910985276879143786" data-theme="dark" data-showcoverphoto="false" data-rel="author"></div>

<!-- Place this tag after the last widget tag. -->
<script type="text/javascript">
  window.___gcfg = {lang: 'en-GB'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
