#!/bin/bash
cd $HOME && \
git clone git@github.com:chiselwright/bashrcd.git .bashrc.d && \
git clone git@github.com:chiselwright/vimrc.git .vim && \
ln -s $HOME/.vim/vimrc $HOME/.vimrc && \
tail -n 8 $HOME/.bashrc.d/README.bashrc >> $HOME/.bashrc && \
source $HOME/.bashrc
